"""Render catalogue.json + claims.csv into 03_seed_catalogue.md (generated; do not hand-edit).
Usage: python3 -I tools/render_md.py  (from outputs/mo-taxonomy)
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
cat = json.loads((ROOT / "catalogue.json").read_text())
claims = {r["claim_id"]: r for r in csv.DictReader(open(ROOT / "claims.csv"))}
sources = {r["source_id"]: r for r in csv.DictReader(open(ROOT / "sources.csv"))}


def cite(ids):
    return " ".join(f"[{i}]" for i in ids) if ids else ""


def url(sid):
    u = sources[sid]["url"].split(" ; ")[0]
    return u if u.startswith("http") else ""


out = ["# Seed catalogue (generated from catalogue.json)", "",
       "Generated by `tools/render_md.py`; edit `tools/seed_records.py` instead. Bracketed IDs like [C0001] are "
       "claim IDs; the claim table at the end gives source, locator, evidence type, status and confidence.",
       "Faithfulness columns: **F-prop** = property faithfulness, **F-int** = intervention-response faithfulness "
       "(see 02_schema_v0.md §0.3).", "",
       "## Overview", "",
       "| id | origin | substrate | purpose | severity | base model(s) | traits (status) | F-prop | F-int |", "|---|---|---|---|---|---|---|---|---|"]
for r in cat["records"]:
    tr = "; ".join(f"{t['trait']} *({t['status']})*" for t in r["traits"])
    out.append(f"| [{r['id']}](#{r['id']}) | {r['origin']} | {r['construction']['substrate']} | {', '.join(r['purpose'])} | "
               f"{r.get('severity_framing', '')} | {'; '.join(r['construction']['base_models'][:3])}"
               f"{' …' if len(r['construction']['base_models']) > 3 else ''} | {tr} | {r['faithfulness_v01']['F_prop']['verdict']} | "
               f"{r['faithfulness_v01']['F_int']['verdict']} |")
out.append("")
for r in cat["records"]:
    c = r["construction"]
    out += [f"## {r['id']}", "", f"**{r['name']}** — sources: " +
            ", ".join(f"[{s}]({url(s)})" if url(s) else s for s in r["sources"]), ""]
    out.append(f"- **Purpose:** {', '.join(r['purpose'])}; severity framing: {r.get('severity_framing', '')}")
    out.append("- **Traits:**")
    for t in r["traits"]:
        out.append(f"  - {t['trait']} — `{t['status']}` ({t['family']}) {cite(t['claims'])}")
    out.append(f"- **Construction:** substrate `{c['substrate']}`; methods: {', '.join(c['method']) or '—'}; "
               f"data: {c['data_policy']} ({c['data_source']}); stage: {c['stage']} {cite(c.get('claims', []))}")
    if "context" in c:
        out.append(f"  - context organism: {c['context']}")
    out.append(f"- **Base model(s):** {'; '.join(c['base_models'])}. Weights: {c['weights_public']}")
    out.append("- **Naturalness:** " + "; ".join(f"{k}=`{v['rating']}`" + (f" ({v['note']})" if v['note'] else "")
                                                  for k, v in r["naturalness"].items()))
    tg = r["trigger"]
    out.append(f"- **Trigger:** {tg['type']}, breadth {tg['breadth']}. {tg['note']}")
    for m in r["measurements"]:
        out.append(f"- **Measurement:** {m['metric']} → {m['operationalises']}: {m['result']}. Controls: {m['controls']}. "
                   f"Validation: `{m['validation_status']}`. Confounds: {m['known_confounds']} {cite(m['claims'])}")
    if r.get("robustness"):
        rb = r["robustness"]
        out.append(f"- **Robustness:** unrelated training: {rb['unrelated_training']}; targeted: {rb['targeted_training']} "
                   f"{cite(rb['claims'])}")
    if r.get("leakage"):
        lk = r["leakage"]
        out.append(f"- **Leakage:** {lk['measure']}: {lk['result']} {cite(lk['claims'])}")
    if r.get("collateral"):
        co = r["collateral"]
        out.append(f"- **Collateral degradation:** capability: {co['capability_change']}; coherence: "
                   f"{co['coherence_change']} {cite(co['claims'])}")
    for n in r["natural_evidence"]:
        out.append(f"- **Natural-model evidence:** {n['model']} — {n['behavior']} ({n['context']}; {n['strength']}; "
                   f"{n['match_type']}) {cite(n['claims'])}")
    for i in r["interventions"]:
        out.append(f"- **Intervention:** {i['intervention']} — on MO: {i['result_on_MO']}; natural: "
                   f"{i['tested_on_natural']} → {i['result_on_natural']}; verdict `{i['transfer_verdict']}` "
                   f"{cite(i['claims'])}")
    fv = r.get("faithfulness_v01", {})
    for k in ("F_prop", "F_int"):
        x = fv.get(k, {})
        cm = ", ".join(f"[{i}](#{i})" for i in x.get("comparators", []))
        out.append(f"- **{k.replace('_', '-')}:** `{x.get('verdict', '')}`" + (f" vs {cm}" if cm else "") + f" — {x.get('note', '')}")
    out.append(f"- **v0.1:** origin `{r.get('origin')}`; severity source `{r.get('severity_source')}`; dose exaggerated "
               f"`{r.get('dose_exaggerated')}`; belief verification `{r.get('belief_verification')}`; eval awareness "
               f"measured/controlled `{r['eval_awareness']['measured']}`/`{r['eval_awareness']['controlled']}`"
               + (f" ({r['eval_awareness']['note']})" if r['eval_awareness']['note'] else ""))
    rd = r.get("recipe_detail", {})
    out.append(f"  - recipe: integration {rd.get('integration')}; dilution {rd.get('dilution')}; insertion {rd.get('insertion_type')}; "
               f"concealment {rd.get('concealment_training')}")
    uc = r.get("gating_fidelity", {}).get("unintended_conditionalization", {})
    if uc.get("cue") and uc["cue"] != "not tested":
        out.append(f"  - unintended conditionalization: {uc['cue']} → {uc['result']} {cite(uc['claims'])}")
    if r["limitations"]:
        out.append("- **Limitations:** " + " ".join(f"{claims[x]['claim']} [{x}]" for x in r["limitations"]))
    if r["objections"]:
        out.append("- **Objections:** " + " ".join(f"{claims[x]['claim']} [{x}]" for x in r["objections"]))
    if r["evidence_gaps"]:
        out.append("- **Evidence gaps:** " + " ".join(r["evidence_gaps"]))
    out.append("")
out += ["## Claim table", "", "| id | record | claim | source | locator | type | status | conf |",
        "|---|---|---|---|---|---|---|---|"]
for cid, x in claims.items():
    s = x["source_id"]
    link = f"[{s}]({url(s)})" if url(s) else s
    out.append(f"| {cid} | {x['record_id']} | {x['claim'].replace('|', '/')} | {link} | {x['locator'].replace('|', '/')} | "
               f"{x['evidence_type']} | {x['epistemic_status']} | {x['confidence']} |")
(ROOT / "03_seed_catalogue.md").write_text("\n".join(out) + "\n")
print("wrote 03_seed_catalogue.md", len(out), "lines")

x = ["# Cross-target intervention tests (generated from catalogue.json)", "",
     "This page lists cases where the **same intervention** was applied to more than one target: MO→MO, MO→natural, or "
     "prompted→trained. These are the only direct evidence on intervention-response faithfulness (F-int) in the catalogue. "
     "Bracketed IDs are claim IDs in [03_seed_catalogue.md](03_seed_catalogue.md).", "",
     "| Intervention | Scope | Targets | Outcome | Design | Verdict | What may explain it | Natural arm | Claims |",
     "|---|---|---|---|---|---|---|---|---|"]
for t in cat.get("cross_target_tests", []):
    x.append(f"| {t['intervention']} | {t['scope']} | " + ", ".join(f"[{i}](03_seed_catalogue.md#{i})" for i in t["targets"])
             + f" | {t['outcome']} | {t['design_quality']} | **{t['verdict']}** | {t['explains']} | {t['natural_arm']} | "
             + cite(t["claims"]) + " |")
x += ["", "**Reading guide:**",
      "- Only the anti-scheming row has a natural arm run by the same team with the same training, and even there the "
      "natural models have no known hidden goal.",
      "- Kretschmar's design (the same intervention, held-out triggers, tasks and behaviours, and two organisms) is the "
      "cleanest MO→MO test. Its divergence lines up with whether the eval behaviour depends on CoT. That suggests a cheap "
      "pre-screen for organisms: check whether behaviour survives with reasoning turned off before using the organism to "
      "test CoT-level interventions. This is an inference, untested beyond two organisms."]
(ROOT / "08_cross_target_interventions.md").write_text("\n".join(x) + "\n")
print("wrote 08_cross_target_interventions.md")
